# This file contains settings necessary to deploy private version of TWAIN Cloud. 
# Update values as instructed below befoe the deployment.

# Get API Gateway URL for deployed APIs
TWAIN_API: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}" ] ]  }
# Retrieive TWAIN Cloud Website URL
TWAIN_WEB: { "Fn::GetAtt": [ WebSiteBucket, WebsiteURL ] }

#region Manual Update

# Pick from AWS console IoT -> Settings -> Endpoint
# https://github.com/hazy-bits/twain-cloud/wiki/%5BConfiguration%5D-IoT-Endpoint
TWAIN_IOT_ENDPOINT: TODO

# Setup Facebook Login application as described here:
# https://github.com/hazy-bits/twain-cloud/wiki/%5BConfiguration%5D-Facebook-Authentication
PROVIDER_FACEBOOK_ID: TODO
PROVIDER_FACEBOOK_SECRET: TODO

# Setup Google OAuth2 client as described here:
# https://github.com/hazy-bits/twain-cloud/wiki/%5BConfiguration%5D-Google-Authentication
PROVIDER_GOOGLE_ID: TODO
PROVIDER_GOOGLE_SECRET: TODO

# Access Token Secret is used to generate JWT tokens. Any arbitrary string would do.
# Keep you secret in a safe place! 
ACCESS_TOKEN_SECRET: TODO

#endregion